### ISSUE TITLE
Failed to load gripper_controller

### ISSUE THREAD

**Issue by shouji000** [moudallal/venbot#1]
hello! how can I deal with it
 [ERROR] [1718354461.811643, 0.000000]: Failed to load gripper_controller
[ERROR] [1718354460.810204444]: Could not load controller 'gripper_controller' because controller type 'effort_controllers/GripperActionController' does not exist.

**Comment by moudallal** [comment]
Hey @shouji000, sorry for the late reply, I was on vacation. 
Can you provide more details about the full error log and the ROS version you're on?

Did you also try to install ROS effort controllers through `apt-get`?

**Comment by shouji000** [comment]
sorry,i just noticed your answer,i have fixed the bug by installing gripper_controller.Thank you very much. @moudallal

**Comment by moudallal** [comment]
Hey @shouji000, I'm glad you figured it out. I'm closing this issue since you've already resolved it. If you manage to add any new functionalities or features to the project, feel free to create a pull request and reach out! Good luck!
